# Generated by Django 5.1.4 on 2025-01-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='game_type',
            field=models.CharField(max_length=255),
        ),
    ]
